services:
  backend:
    container_name: backend
    build: .
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    logging:
      driver: "local"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:alpine
    restart: unless-stopped
    logging:
      driver: "local"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
      
volumes:
  pgdata: