services:
  backend:
    container_name: backend
    build: .
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    logging:
      driver: "local"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:alpine
    restart: unless-stopped
    logging:
      driver: "local"
    env_file:
      - .env
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
      
volumes:
  pgdata: