name: CI

on:
  push:
    branches: [ "main" ]

jobs:

  pull-and-run:
    runs-on: [self-hosted] 
    steps:
    - name: Update server to latest commit
      run: | 
        cd /home/neighbourpro/neighbourpro-backend &&\
        docker compose down &&\
        docker image prune -a --force &&\
        git pull &&\
        git submodule update --init --recursive &&
        docker compose up -d --build --force-recreate
